"""empty message

Revision ID: 06e5c8690286
Revises: 7381cc269531
Create Date: 2026-03-09 15:51:56.665443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e5c8690286'
down_revision: Union[str, Sequence[str], None] = '7381cc269531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advisory_activity', 'organ_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('advisory_activity', 'start_year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advisory_activity', 'start_year',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('advisory_activity', 'organ_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
