"""empty message

Revision ID: 7381cc269531
Revises: e2762132f61b
Create Date: 2026-03-09 13:00:53.443433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7381cc269531'
down_revision: Union[str, Sequence[str], None] = 'e2762132f61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('software_code_key'), 'software', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('software_code_key'), 'software', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
