"""empty message

Revision ID: 9fb486be01c0
Revises: 06e5c8690286
Create Date: 2026-04-16 09:58:00.776877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb486be01c0'
down_revision: Union[str, Sequence[str], None] = '06e5c8690286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patent_code_key'), 'patent', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('patent_code_key'), 'patent', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
